# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\jenny\Desktop\code_practise\pyqt_pra\ui\my_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(532, 364)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/mainLogo"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 532, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen_file = QtWidgets.QAction(MainWindow)
        self.actionopen_file.setObjectName("actionopen_file")
        self.actionopen_fold = QtWidgets.QAction(MainWindow)
        self.actionopen_fold.setObjectName("actionopen_fold")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actioncancel = QtWidgets.QAction(MainWindow)
        self.actioncancel.setObjectName("actioncancel")
        self.actionrefresh = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/refresh"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionrefresh.setIcon(icon1)
        self.actionrefresh.setObjectName("actionrefresh")
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.menu.addAction(self.actionopen_file)
        self.menu.addAction(self.actionopen_fold)
        self.menu.addAction(self.actionsave)
        self.menu.addAction(self.actionexit)
        self.menu_2.addAction(self.actioncancel)
        self.menu_2.addAction(self.actionrefresh)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(self.spinBox.stepUp) # type: ignore
        self.pushButton_2.clicked.connect(self.spinBox.stepDown) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "小确幸"))
        self.pushButton.setText(_translate("MainWindow", "up"))
        self.pushButton_2.setText(_translate("MainWindow", "down"))
        self.pushButton_3.setText(_translate("MainWindow", "count"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.menu_3.setTitle(_translate("MainWindow", "关于我们"))
        self.actionopen_file.setText(_translate("MainWindow", "open file"))
        self.actionopen_fold.setText(_translate("MainWindow", "open fold"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actioncancel.setText(_translate("MainWindow", "cancel"))
        self.actionrefresh.setText(_translate("MainWindow", "刷新"))
        self.actionexit.setText(_translate("MainWindow", "exit"))
# import resource_rc
