# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\jenny\Desktop\code_practise\pyqtLife\ui\net_assist_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NetAssistWidget(object):
    def setupUi(self, NetAssistWidget):
        NetAssistWidget.setObjectName("NetAssistWidget")
        NetAssistWidget.resize(604, 430)
        self.groupBox = QtWidgets.QGroupBox(NetAssistWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 232, 140))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.Label = QtWidgets.QLabel(self.groupBox)
        self.Label.setObjectName("Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.cb_mode = QtWidgets.QComboBox(self.groupBox)
        self.cb_mode.setObjectName("cb_mode")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_mode)
        self.iPLabel = QtWidgets.QLabel(self.groupBox)
        self.iPLabel.setObjectName("iPLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.iPLabel)
        self.edit_ip = QtWidgets.QLineEdit(self.groupBox)
        self.edit_ip.setObjectName("edit_ip")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit_ip)
        self.Label_2 = QtWidgets.QLabel(self.groupBox)
        self.Label_2.setObjectName("Label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.edit_target_port = QtWidgets.QLineEdit(self.groupBox)
        self.edit_target_port.setObjectName("edit_target_port")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.edit_target_port)
        self.verticalLayout.addLayout(self.formLayout)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.textEdit = QtWidgets.QTextEdit(NetAssistWidget)
        self.textEdit.setGeometry(QtCore.QRect(243, 10, 331, 161))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(NetAssistWidget)
        self.textEdit_2.setGeometry(QtCore.QRect(243, 210, 261, 111))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton = QtWidgets.QPushButton(NetAssistWidget)
        self.pushButton.setGeometry(QtCore.QRect(513, 210, 61, 111))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(NetAssistWidget)
        self.label.setGeometry(QtCore.QRect(243, 180, 54, 16))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(NetAssistWidget)
        self.comboBox.setGeometry(QtCore.QRect(290, 180, 131, 22))
        self.comboBox.setObjectName("comboBox")
        self.label_2 = QtWidgets.QLabel(NetAssistWidget)
        self.label_2.setGeometry(QtCore.QRect(436, 180, 61, 20))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(NetAssistWidget)
        self.lineEdit.setGeometry(QtCore.QRect(505, 180, 71, 20))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(NetAssistWidget)
        QtCore.QMetaObject.connectSlotsByName(NetAssistWidget)

    def retranslateUi(self, NetAssistWidget):
        _translate = QtCore.QCoreApplication.translate
        NetAssistWidget.setWindowTitle(_translate("NetAssistWidget", "Form"))
        self.groupBox.setTitle(_translate("NetAssistWidget", "网络设置"))
        self.Label.setText(_translate("NetAssistWidget", "设置模式："))
        self.iPLabel.setText(_translate("NetAssistWidget", "服务器IP："))
        self.Label_2.setText(_translate("NetAssistWidget", "服务器端口："))
        self.pushButton_2.setText(_translate("NetAssistWidget", "连接服务器"))
        self.pushButton.setText(_translate("NetAssistWidget", "发送"))
        self.label.setText(_translate("NetAssistWidget", "本地IP："))
        self.label_2.setText(_translate("NetAssistWidget", "本地端口："))
