# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\jenny\Desktop\code_practise\pyqtLife\ui\serial_assist_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SerialAssistWidget(object):
    def setupUi(self, SerialAssistWidget):
        SerialAssistWidget.setObjectName("SerialAssistWidget")
        SerialAssistWidget.resize(525, 448)
        self.comboBox = QtWidgets.QComboBox(SerialAssistWidget)
        self.comboBox.setGeometry(QtCore.QRect(120, 170, 68, 22))
        self.comboBox.setObjectName("comboBox")
        self.tableView = QtWidgets.QTableView(SerialAssistWidget)
        self.tableView.setGeometry(QtCore.QRect(190, 120, 256, 192))
        self.tableView.setObjectName("tableView")
        self.groupBox = QtWidgets.QGroupBox(SerialAssistWidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 40, 120, 80))
        self.groupBox.setObjectName("groupBox")

        self.retranslateUi(SerialAssistWidget)
        QtCore.QMetaObject.connectSlotsByName(SerialAssistWidget)

    def retranslateUi(self, SerialAssistWidget):
        _translate = QtCore.QCoreApplication.translate
        SerialAssistWidget.setWindowTitle(_translate("SerialAssistWidget", "Form"))
        self.groupBox.setTitle(_translate("SerialAssistWidget", "GroupBox"))
